% Compile Injective 2D
mex lim_solver_mex.cpp ...
    ../src/TriangleMesh.cpp ...
	../src/TetrahedronMesh.cpp ...
	../src/NMSolver.cpp ...
    ../src/LIMSolver.cpp ...
	../src/LIMSolver2D.cpp ...
	../src/LIMSolver3D.cpp ...
	../src/Identity_LIMSolver2D.cpp ...
	../src/Dirichlet_LIMSolver2D.cpp ...
	../src/UniformLaplacian_LIMSolver2D.cpp ...
	../src/Laplacian_LIMSolver2D.cpp ...
	../src/GreenStrain_LIMSolver2D.cpp ...
	../src/LGARAP_LIMSolver2D.cpp ...
	../src/LSConformal_LIMSolver2D.cpp ...
    ../src/Poisson_LIMSolver2D.cpp ...
	../src/Identity_LIMSolver3D.cpp ...
	../src/Dirichlet_LIMSolver3D.cpp ...
	../src/UniformLaplacian_LIMSolver3D.cpp ...
	../src/Laplacian_LIMSolver3D.cpp ...
	../src/GreenStrain_LIMSolver3D.cpp ...
    ../src/LGARAP_LIMSolver3D.cpp ...
	../src/wunderSVD/WunderSVD3x3.cpp ...
    ../src/wunderSVD/Procrustes.cpp ...
    -I../src ...
    -ID:/data/libraries/libigl/include ...
    -ID:/data/libraries/Eigen ...
    -I../../libigl/include ...
    -I/opt/local/include/eigen3 ...
%    -g % enable debugging

%%
mex lim_solver_mex_step.cpp ...
    ../src/TriangleMesh.cpp ...
	../src/TetrahedronMesh.cpp ...
	../src/NMSolver.cpp ...
    ../src/LIMSolver.cpp ...
	../src/LIMSolver2D.cpp ...
	../src/LIMSolver3D.cpp ...
	../src/Identity_LIMSolver2D.cpp ...
	../src/Dirichlet_LIMSolver2D.cpp ...
	../src/UniformLaplacian_LIMSolver2D.cpp ...
	../src/Laplacian_LIMSolver2D.cpp ...
	../src/GreenStrain_LIMSolver2D.cpp ...
	../src/LGARAP_LIMSolver2D.cpp ...
	../src/LSConformal_LIMSolver2D.cpp ...
    ../src/Poisson_LIMSolver2D.cpp ...
	../src/Identity_LIMSolver3D.cpp ...
	../src/Dirichlet_LIMSolver3D.cpp ...
	../src/UniformLaplacian_LIMSolver3D.cpp ...
	../src/Laplacian_LIMSolver3D.cpp ...
	../src/GreenStrain_LIMSolver3D.cpp ...
    ../src/LGARAP_LIMSolver3D.cpp ...
	../src/wunderSVD/WunderSVD3x3.cpp ...
    ../src/wunderSVD/Procrustes.cpp ...
    -I../src ...
    -ID:/data/libraries/libigl/include ...
    -ID:/data/libraries/Eigen ...
    -I../../libigl/include ...
    -I/opt/local/include/eigen3 ...
%    -g % enable debugging
